Name:           perl-CGI-PSGI
Version:        0.15
Release:        1%{?dist}
Summary:        Adapt CGI.pm to the PSGI protocol
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/CGI-PSGI/
Source0:        http://www.cpan.org/modules/by-module/CGI/CGI-PSGI-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 1:5.8.1
BuildRequires:  perl(CGI) >= 3.33
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Test::More) >= 0.88
Requires:       perl(CGI) >= 3.33
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module is for web application framework developers who currently uses
CGI to handle query parameters, and would like for the frameworks to comply
with the PSGI protocol.

%prep
%setup -q -n CGI-PSGI-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Sun Feb 02 2025 Michael R. Davis <mrdvt92@yahoo.com> 0.15-1
- Specfile autogenerated by cpanspec 1.78.
